source 'https://supermarket.chef.io'

cookbook 'openssl',           '~> 7.1.0'
cookbook 'nginx',             '~> 7.0.0'
cookbook 'poise-python',      '~> 1.6.0'
cookbook 'nodejs',            '~> 4.0.0'
cookbook 'acme',              '~> 3.1.0'

cookbook 'genome_scipy_base', path: '../genome_scipy_base'
cookbook 'genome_scipy_github', path: '../genome_scipy_github'
cookbook 'genome_scipy_openssl', path: '../genome_scipy_openssl'
cookbook 'genome_scipy_nginx', path: '../genome_scipy_nginx'
cookbook 'genome_scipy_nodejs', path: '../genome_scipy_nodejs'
cookbook 'genome_scipy_python', path: '../genome_scipy_python'
cookbook 'genome_scipy_supervisor', path: '../genome_scipy_supervisor'
cookbook 'genome_scipy_docker', path: '../genome_scipy_docker'

metadata
