source 'https://supermarket.chef.io'

cookbook 'genome_scipy_app', path: 'chef-repo/wrapper_cookbooks/genome_scipy_app' 
cookbook 'genome_scipy_jupyterhub', path: 'chef-repo/wrapper_cookbooks/genome_scipy_jupyterhub'
cookbook 'genome_scipy_jupyter', path: 'chef-repo/wrapper_cookbooks/genome_scipy_jupyter'
cookbook 'genome_scipy_base', path: 'chef-repo/wrapper_cookbooks/genome_scipy_base'  
cookbook 'genome_scipy_github', path: 'chef-repo/wrapper_cookbooks/genome_scipy_github'
cookbook 'genome_scipy_nginx', path: 'chef-repo/wrapper_cookbooks/genome_scipy_nginx'
cookbook 'genome_scipy_openssl', path: 'chef-repo/wrapper_cookbooks/genome_scipy_openssl'
cookbook 'genome_scipy_python', path: 'chef-repo/wrapper_cookbooks/genome_scipy_python'
cookbook 'genome_scipy_nodejs', path: 'chef-repo/wrapper_cookbooks/genome_scipy_nodejs'
cookbook 'genome_scipy_supervisor', path: 'chef-repo/wrapper_cookbooks/genome_scipy_supervisor' 
cookbook 'genome_scipy_hosts', path: 'chef-repo/wrapper_cookbooks/genome_scipy_hosts'  
cookbook 'genome_scipy_aws', path: 'chef-repo/wrapper_cookbooks/genome_scipy_aws'    
